### ISSUE TITLE
Assignment 2 Ready for Grading

### ISSUE THREAD

**Issue by Li-Aijing** [SES-5215-F2020/aijingli-quant#2]
Hi Carole and Sara,

I have pushed my files for assignment 2 into my repo. Looking forward to your comments!

Thanks,
Aijing

**Comment by saratepfer** [comment]
Thank you, Aijing! Really nice job on this! A few comments on code, below:

- Line 86: I would add ", digits = 3" to the prettynum function for your median display, to prevent R from printing too many numbers after the decimal place.
- Line 137: add an extra return here to allow your interpretation to begin on a different line than the plot.
